
FROM eclipse-mosquitto

ENV http_proxy=http://proxy.sthdg.local:8080
ENV https_proxy=http://proxy.sthdg.local:8080

RUN apk add --update openssl
RUN apk add bash

ENV SSL_PATH=/ssl/mosquitto

WORKDIR $SSL_PATH

#RUN echo "PS1='[\u@\h \W]\\$ '" >> .bashrc'